version: '3.4'

services:
  bcfinalmoviecatalogsvc:
    image: ${DOCKER_REGISTRY-}bcfinalmoviecatalogsvc
    build:
      context: .
      dockerfile: src/BcFinalMovieCatalogSvc/Dockerfile
    networks:
      - local-shared

networks:
  local-shared:
    external:
        name: bc-localdevelopment_network-to-share